server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/oina}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}

integration:
  inventory:
    url: ${INVENTORY_URL:http://localhost:8081}

order:
  auto-cancel-minutes: ${ORDER_AUTO_CANCEL_MINUTES:30}

schedule:
  cancel-unpaid-orders-cron: ${CANCEL_UNPAID_ORDERS_CRON:0 0/5 * * * ?}
