server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/oina}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:b919abc8384c408f4a01f8df62a1dea5f56b2f62b4ffc48257895e5c2ec070d8}

integration:
  inventory:
    url: ${INVENTORY_URL:http://localhost:8081}
  toys-service:
    url: ${TOYS_SERVICE_URL:http://localhost:8084}
  subscription:
    url: ${SUBSCRIPTION_SERVICE_URL:http://localhost:8083}

order:
  auto-cancel-minutes: ${ORDER_AUTO_CANCEL_MINUTES:10000}

schedule:
  cancel-unpaid-orders-cron: ${CANCEL_UNPAID_ORDERS_CRON:0 0/30 * * * ?}
